### ISSUE TITLE
Error while starting api and worker containers

### ISSUE THREAD

**Issue by harshadyeola** [dolaterio/dolaterio#28]
While running the docker compose file I am facing following issues. Please help
```
 ~/Github/dolaterio/ [master] docker-compose up
Starting dolaterio_redis_1
Starting dolaterio_rethinkdb_1
Starting dolaterio_worker_1
Starting dolaterio_api_1
Attaching to dolaterio_redis_1, dolaterio_rethinkdb_1, dolaterio_worker_1, dolaterio_api_1
worker_1     | time="2016-06-02T06:47:17Z" level=warning msg="Error creating connection dial tcp 172.17.0.3:28015: connection refused" 
worker_1     | panic: no connections were made when creating the session
worker_1     | 
worker_1     | goroutine 1 [running]:
worker_1     | main.main()
redis_1      | [1] 02 Jun 06:47:17.726 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
api_1        | time="2016-06-02T06:47:17Z" level=warning msg="Error creating connection dial tcp 172.17.0.3:28015: connection refused" 
worker_1     | 	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/worker/main.go:13 +0x77
redis_1      |                 _._                                                  
api_1        | time="2016-06-02T06:47:17Z" level=fatal msg="Failure connecting to the db" err="no connections were made when creating the session" package=api 
redis_1      |            _.-``__ ''-._        
```

**Comment by acroca** [comment]
Interesting. Perhaps it needs some delay to make sure the DB is up and running. Can you try to run redis and rethinkdb first, wait a few seconds and then run the api and the worker?

**Comment by harshadyeola** [comment]
@acroca 
First of all sorry for this much delayed response!
I tried that still following issue exists. I think dolaterio database is missing?
Anyway to fix that?
```github.com/rethinkdb/rethinkdb/releases>.
worker_1     | panic: gorethink: Database `dolaterio` does not exist. in: 
worker_1     | r.Wait()
worker_1     | 
worker_1     | goroutine 1 [running]:
worker_1     | main.main()
worker_1     | 	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/worker/main.go:13 +0x77
worker_1     | 
worker_1     | goroutine 5 [chan receive]:
worker_1     | github.com/dancannon/gorethink.(*Pool).connectionOpener(0xc20806d400)
worker_1     | 	/Users/albert/workspace/gocode/src/github.com/dancannon/gorethink/pool.go:200 +0x4c
worker_1     | created by github.com/dancannon/gorethink.NewPool
worker_1     | 	/Users/albert/workspace/gocode/src/github.com/dancannon/gorethink/pool.go:69 +0x1cc
worker_1     | 
worker_1     | goroutine 6 [runnable]:
worker_1     | github.com/dancannon/gorethink.newNode.func1(0x6fc23ac00, 0xc208086900)
worker_1     | 	/Users/albert/workspace/gocode/src/github.com/dancannon/gorethink/node.go:47
worker_1     | created by github.com/dancannon/gorethink.newNode
worker_1     | 	/Users/albert/workspace/gocode/src/github.com/dancannon/gorethink/node.go:57 +0x1e7
api_1        | time="2016-07-27T09:20:54Z" level=fatal msg="Failure connecting to the db" err="gorethink: Database `dolaterio` does not exist. in: \nr.Wait()" package=api 
dolaterio_worker_1 exited with code 2
dolaterio_api_1 exited with code 1```

**Comment by harshadyeola** [comment]
So here is what I did in order to run redis and rethinkdb befor dolaterio api & worker
```
replaced `links` with `depends_on`
depends_on:
        - rethinkdb
        - redis
```
But still not working.
However following this doc works perfectly. Not sure whats wrong with docker-compose. https://github.com/dolaterio/dolaterio/blob/master/docs/run.md

**Comment by acroca** [comment]
You are right. The docker compose piece doesn't have the migration step, and without migration the database is not created.
I'm not 100% sure what's the best way to do that using docker compose. As a temporary solution you can run the migration manually and then restart the services.

**Comment by harshadyeola** [comment]
@acroca 
Thanks man for pointing out to migration step. I will fix this and send PR

**Comment by harshadyeola** [comment]
@acroca Fixed the issue :). Please review and merge PR sent.
