### ISSUE TITLE
Docker 1.12 : Support for Docker Swarm mode.

### ISSUE THREAD

**Issue by harshadyeola** [dolaterio/dolaterio#30]
Docker v1.12 releases a lot many features including support for swarm mode in docker engine itself. This might help in resolving issue like #27 .

**Comment by harshadyeola** [comment]
Also after upgrading to docker v1.12 the workers are not getting executed.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x45ec7f]

goroutine 9 [running]:
github.com/dolaterio/dolaterio/runner.Run(0xc208086d00, 0xc208011aa0, 0x0, 0x0)
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/run.go:17 +0x66f
github.com/dolaterio/dolaterio/runner.(*JobRunner).run(0xc20800f220)
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:99 +0x105
created by github.com/dolaterio/dolaterio/runner.(*JobRunner).Start
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:52 +0x4d

goroutine 1 [chan receive]:
main.main()
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/worker/main.go:33 +0x3de

goroutine 5 [chan receive]:
github.com/dancannon/gorethink.(*Pool).connectionOpener(0xc20806d680)
	/Users/albert/workspace/gocode/src/github.com/dancannon/gorethink/pool.go:200 +0x4c
created by github.com/dancannon/gorethink.NewPool
	/Users/albert/workspace/gocode/src/github.com/dancannon/gorethink/pool.go:69 +0x1cc

goroutine 6 [select]:
github.com/dancannon/gorethink.newNode.func1(0x6fc23ac00, 0xc208086900)
	/Users/albert/workspace/gocode/src/github.com/dancannon/gorethink/node.go:50 +0x10c
created by github.com/dancannon/gorethink.newNode
	/Users/albert/workspace/gocode/src/github.com/dancannon/gorethink/node.go:57 +0x1e7

goroutine 8 [sleep]:
time.Sleep(0x3b9aca00)
	/Users/albert/workspace/go/src/runtime/time.go:59 +0x112
gopkg.in/redis%2ev2.(*rateLimiter).loop(0xc2080e3a50, 0x3b9aca00, 0x14)
	/Users/albert/workspace/gocode/src/gopkg.in/redis.v2/rate_limit.go:30 +0x87
created by gopkg.in/redis%2ev2.newRateLimiter
	/Users/albert/workspace/gocode/src/gopkg.in/redis.v2/rate_limit.go:18 +0x72

goroutine 10 [select]:
github.com/dolaterio/dolaterio/runner.(*JobRunner).run(0xc20800f220)
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:95 +0x1ef
created by github.com/dolaterio/dolaterio/runner.(*JobRunner).Start
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:52 +0x4d

goroutine 11 [select]:
github.com/dolaterio/dolaterio/runner.(*JobRunner).run(0xc20800f220)
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:95 +0x1ef
created by github.com/dolaterio/dolaterio/runner.(*JobRunner).Start
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:52 +0x4d

goroutine 12 [select]:
github.com/dolaterio/dolaterio/runner.(*JobRunner).run(0xc20800f220)
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:95 +0x1ef
created by github.com/dolaterio/dolaterio/runner.(*JobRunner).Start
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:52 +0x4d

goroutine 13 [select]:
github.com/dolaterio/dolaterio/runner.(*JobRunner).run(0xc20800f220)
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:95 +0x1ef
created by github.com/dolaterio/dolaterio/runner.(*JobRunner).Start
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:52 +0x4d

goroutine 14 [select]:
github.com/dolaterio/dolaterio/runner.(*JobRunner).run(0xc20800f220)
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:95 +0x1ef
created by github.com/dolaterio/dolaterio/runner.(*JobRunner).Start
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:52 +0x4d

goroutine 15 [select]:
github.com/dolaterio/dolaterio/runner.(*JobRunner).run(0xc20800f220)
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:95 +0x1ef
created by github.com/dolaterio/dolaterio/runner.(*JobRunner).Start
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:52 +0x4d

goroutine 16 [select]:
github.com/dolaterio/dolaterio/runner.(*JobRunner).run(0xc20800f220)
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:95 +0x1ef
created by github.com/dolaterio/dolaterio/runner.(*JobRunner).Start
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:52 +0x4d

goroutine 17 [IO wait]:
net.runtime_pollWait(0x7fef9a6a87d0, 0x72, 0xc2080f6000)
	/Users/albert/workspace/go/src/runtime/netpoll.go:157 +0x63
net.(*pollDesc).Wait(0xc2080e48b0, 0x72, 0x0, 0x0)
	/Users/albert/workspace/go/src/net/fd_poll_runtime.go:73 +0x41
net.(*pollDesc).WaitRead(0xc2080e48b0, 0x0, 0x0)
	/Users/albert/workspace/go/src/net/fd_poll_runtime.go:78 +0x3d
net.(*netFD).Read(0xc2080e4850, 0xc2080f6000, 0x1000, 0x1000, 0x0, 0x7fef9a6a3050, 0xc20800a130)
	/Users/albert/workspace/go/src/net/fd_unix.go:232 +0x22d
net.(*conn).Read(0xc208026198, 0xc2080f6000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/Users/albert/workspace/go/src/net/net.go:124 +0xe7
gopkg.in/redis%2ev2.(*conn).Read(0xc2080e48c0, 0xc2080f6000, 0x1000, 0x1000, 0xc2080f8300, 0x0, 0x0)
	/Users/albert/workspace/gocode/src/gopkg.in/redis.v2/pool.go:70 +0x17e
gopkg.in/bufio%2ev1.(*Reader).fill(0xc2080148a0)
	/Users/albert/workspace/gocode/src/gopkg.in/bufio.v1/bufio.go:97 +0x1d8
gopkg.in/bufio%2ev1.(*Reader).ReadSlice(0xc2080148a0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/albert/workspace/gocode/src/gopkg.in/bufio.v1/bufio.go:298 +0x23a
gopkg.in/bufio%2ev1.(*Reader).ReadLine(0xc2080148a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/albert/workspace/gocode/src/gopkg.in/bufio.v1/bufio.go:356 +0x56
gopkg.in/redis%2ev2.readLine(0xc2080148a0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/albert/workspace/gocode/src/gopkg.in/redis.v2/parser.go:36 +0x45
gopkg.in/redis%2ev2.parseReply(0xc2080148a0, 0xb04c40, 0x0, 0x0, 0x0, 0x0)
	/Users/albert/workspace/gocode/src/gopkg.in/redis.v2/parser.go:113 +0x5a
gopkg.in/redis%2ev2.(*StringSliceCmd).parseReply(0xc208110660, 0xc2080148a0, 0x0, 0x0)
	/Users/albert/workspace/gocode/src/gopkg.in/redis.v2/command.go:434 +0x46
gopkg.in/redis%2ev2.(*baseClient).run(0xc2080d7a70, 0x7fef9a6a8b48, 0xc208110660)
	/Users/albert/workspace/gocode/src/gopkg.in/redis.v2/redis.go:127 +0x231
gopkg.in/redis%2ev2.(*baseClient).Process(0xc2080d7a70, 0x7fef9a6a8b48, 0xc208110660)
	/Users/albert/workspace/gocode/src/gopkg.in/redis.v2/redis.go:96 +0x4c
gopkg.in/redis%2ev2.(*Client).BLPop(0xc208026190, 0x0, 0xc2080cdee0, 0x1, 0x1, 0x9ce150)
	/Users/albert/workspace/gocode/src/gopkg.in/redis.v2/commands.go:563 +0x391
github.com/dolaterio/dolaterio/queue.(*redisQueue).Dequeue(0xc208011b80, 0xc208014900, 0x0, 0x0)
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/queue/redis.go:64 +0x1df
github.com/dolaterio/dolaterio/runner.(*JobRunner).Start.func1(0xc20800f220)
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:62 +0x61
created by github.com/dolaterio/dolaterio/runner.(*JobRunner).Start
	/Users/albert/workspace/gocode/src/github.com/dolaterio/dolaterio/runner/job_runner.go:76 +0x86
```

**Comment by harshadyeola** [comment]
@acroca need help with this issue.

**Comment by acroca** [comment]
Have you tried to figure out what's the issue? More info other than just the stack trace would be very useful.

**Comment by harshadyeola** [comment]
@acroca 
The status of job always shows queued and when checked for logs then above stacktrace is there.
Let me know what I should look for that will help you more in debugging?

**Comment by acroca** [comment]
https://github.com/dolaterio/dolaterio/blob/master/runner/run.go#L17
Can you check what's the `nil` in that line?
I don't have the time to debug your issue but I can assist you with specific problems you run into.

**Comment by harshadyeola** [comment]
@acroca 
Thank you for quick response. Figured out issue. quite silly but forgot to provide worker id within quotes. that caused issue.

**Comment by acroca** [comment]
Ok, no worries
